version: "3.8"
services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__LocalConnection: Server=postgres;Database=truckiDb;User ID=trucki;Password=12345;Port=5432
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: trucki
      POSTGRES_DB: truckiDb
    restart: always
    volumes:
      - postgres_datab:/var/lib/postgresql/data
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge
    

volumes:
  postgres_datab: