version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: trucki
      POSTGRES_DB: trucki_DB
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      ConnectionStrings__LocalConnection: Server=postgres;Database=trucki_DB;User ID=trucki;Password=12345;Port=5432
    ports:
      - "8080:80"

volumes:
  postgres_data:

