# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trucki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://truckireg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4adcdb40343f4d4c903838760fe9f9d2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7f0b48fb174d496a80fcba5d69900969 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: truckireg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4adcdb40343f4d4c903838760fe9f9d2 }}/truckitechnologylimitedtruckiapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trucki'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc29e6ab02334e8f9de75c58ddb2089d }}
        images: 'truckireg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4adcdb40343f4d4c903838760fe9f9d2 }}/truckitechnologylimitedtruckiapi:${{ github.sha }}'